tap "agavra/tap"
tap "asmvik/formulae", "https://github.com/asmvik/homebrew-formulae.git", trusted: true
tap "atomicjar/tap", trusted: true
tap "catppuccin/tap", trusted: true
tap "derailed/k9s", trusted: true
tap "dlvhdr/formulae", trusted: { formulae: ["diffnav"] }
tap "docker/tap", trusted: true
tap "felixkratz/formulae", "https://github.com/FelixKratz/homebrew-formulae", trusted: true
tap "gromgit/brewtils", trusted: true
tap "manaflow-ai/cmux", trusted: true
tap "mvndaemon/mvnd", trusted: true
tap "nikitabobko/tap", trusted: true

brew "awscli"
brew "bat"
brew "btop"
brew "carapace"
brew "cloc"
brew "dive"
brew "eksctl"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "herdr"
brew "httpie"
brew "jq"
brew "k6"
brew "ktlint"
brew "lazydocker"
brew "lazygit"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "ollama"
brew "opencode"
brew "openspec"
brew "pass"
brew "pi-coding-agent"
brew "quien"
brew "rustup"
brew "skm"
brew "sniffnet"
brew "starship"
brew "stow"
brew "superfile"
brew "uv"
brew "wireshark", link: false
brew "yazi"
brew "zellij"
brew "zoxide"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "agavra/tap/tuicr", trusted: true
brew "derailed/k9s/k9s"
brew "felixkratz/formulae/borders"
brew "gromgit/brewtils/taproom"
brew "mvndaemon/mvnd/mvnd"

cask "nikitabobko/tap/aerospace", trusted: true
cask "basictex"
cask "betterdisplay"
cask "brave-browser"
cask "brewy"
cask "calibre"
cask "cmux"
cask "fluidvoice"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "freelens"
cask "ghostty", args: { appdir: "~/Applications" }
cask "github"
cask "gitkraken"
cask "hyperkey"
cask "jetbrains-toolbox"
cask "keystore-explorer"
cask "libreoffice"
cask "libreoffice-language-pack"
cask "lm-studio"
cask "marta"
cask "mitmproxy"
cask "mongodb-compass"
cask "pearcleaner"
cask "pgadmin4"
cask "docker/tap/sbx", trusted: true
cask "shichizip"
cask "sublime-text"
cask "zed"

npm "@earendil-works/pi-coding-agent"
npm "@gotgenes/pi-permission-system"
